### ISSUE TITLE
DOES NOT WORK

### ISSUE THREAD

**Issue by paginabianca** [martin-fink/rust-wkd-server#2]
keys named by their wkd-hash are not served

plz fix now 😠

**Comment by paginabianca** [comment]
Still no fix @martin-fink ... ☹️🥲

**Comment by paginabianca** [comment]
Still no fix @martin-fink

**Comment by paginabianca** [comment]
I use this code for my payed products making millions in dollars in revenue.

I demand fix now my work depends on this 😠😠

**Comment by martin-fink** [comment]
This is not a bug, this is intended to work this way. See the documentation: https://github.com/martin-fink/rust-wkd-server/blob/0a928f6326b146787ba7cac0f32e31e71a293f51/README.md?plain=1#L9-L18

**Comment by paginabianca** [comment]
😒😒😒 Ugh, hey there 🙋‍♀️ Mr. Maintainer 🙋‍♂️. I just wanted to take a quick moment ⏰ to express my sincerest gratitude 🙏 for your incredible contribution 🤝 to my project by closing 🚪 the 🐛 "bug" 🐛 that I reported.

I mean, who needs bug fixes when we can just call them "intended behavior," right? 🤷‍♀️ It's so refreshing to see that kind of attitude towards quality control. 🤦‍♂️

Your decision to close the issue without any explanation or clarification is truly inspiring. 🙄 I especially love how you took the time to make sure I understood that the bug was not, in fact, a bug, but was instead the intended behavior. 👌 It's like you're a mind reader or something. 🔮

I'm sure everyone who encounters this "intended behavior" in the future will be just as delighted as I was. 😤

Thanks again for your amazing work, 👨‍💻 Mr. Maintainer 👨‍💻. You truly are a shining star 🌟 in the open source community. 🤩 I hope you continue to bless us all with your infinite wisdom 🧠 and unparalleled expertise 🤓. We are not worthy! 🙌🙌🙌

👋 Peace out, fam 🤙. Keep on keeping on 🏃‍♂️ and never stop being you! 💪
