### ISSUE TITLE
how to access key?

### ISSUE THREAD

**Issue by kaido2ki** [martin-fink/rust-wkd-server#233]
server can't find the key

![screenshot](https://github.com/user-attachments/assets/84a638ba-f52e-48b9-bc42-2a7f13a62e94)

**Comment by martin-fink** [comment]
Hi, can you see the following lines in your log?

```
wkd-server-1  | [2024-05-30T19:03:26Z INFO  wkd_server::keys::db] Added key /openpgp-keys/martin@finkmartin.com.asc to db
wkd-server-1  | [2024-05-30T19:03:26Z INFO  wkd_server::keys::db] Added key /openpgp-keys/m@finkmartin.com.asc to db
```

**Comment by martin-fink** [comment]
Ok, that's good.
So I assume you're behind a proxy? Does the domain in the log line the part behind the `@` in your key? e.g.

```
Serving key for domain example.com, hash xxxxx.
```

should match your key `something@example.com` or `something@example.com.asc`.

**Comment by martin-fink** [comment]
Happy it works now! :)
