### ISSUE TITLE
🚨 Urgent: Incorrect 'env' Key in Traefic Config! Immediate Action Required! 🚨

### ISSUE THREAD

**Issue by paginabianca** [martin-fink/rust-wkd-server#59]
Issue Description:
Hey there! 👋 It seems like there's a minor hiccup in the example config for Traefik in the repository. The key 'env' is being used, but unfortunately, it doesn't quite match the reality of Docker's configuration structure. 😕

Correction Required:
Instead of 'env', the correct key to be used is 'environment'. This little mix-up could cause some confusion for new users trying to set up Traefic with Docker. Let's make things simpler and smoother for everyone by fixing this small but important issue! 🙌

Action Required:
I kindly request the repository maintainer to please address this issue at your earliest convenience. 🕒 Time is of the essence, and we want to make sure newcomers don't struggle unnecessarily. 💪 Let's maintain the excellence of this repository by ensuring accuracy and clarity in the provided examples.

Thanks a bunch for your quick response and dedication to keeping things shipshape! 🚢 Looking forward to seeing this correction made ASAP. 🚀

Best,
A Concerned Contributor

**Comment by paginabianca** [comment]
Nevermind fixed the issue myself.

**Comment by paginabianca** [comment]
Reopening the issue because @reschandreas thinks it's relevant

**Comment by reschandreas** [comment]
:%s/traefic/traefik/g plz

Also, yes `env` is wrong and even if one fixes it to `environment` the log level does not get set (I suspect). When entering the container and calling `set` the log variable is always the same.

**Comment by paginabianca** [comment]
@reschandreas fixed chat hot sp lling mistakes
